name: webscrapping
on:
  workflow_dispatch:
  schedule:
    - cron:  '00 19 * * *' 

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the respository
      uses: actions/checkout@v3
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Download library 
      run: pip install -r requirements.txt
    - name: Download Chromedriver
      run: |
        curl -O https://chromedriver.storage.googleapis.com/$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
    - name: Run the Python code
      run: python3 main.py Centaline_sale_lease.xlsx
    - name: auto-push to github
      if: always()
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add Centaline_sale_lease.xlsx
        git diff-index --quiet HEAD || git commit -am "archived"
        git push
